export const userActions = {
  EDIT_USER_BIO: 'EDIT_USER_BIO',
  POST_USER_BIO: 'POST_USER_BIO',
  POST_USER_BIO_SUCCESS: 'POST_USER_BIO_SUCCESS',
  POST_USER_BIO_FAILED: 'POST_USER_BIO_FAILED',

  EDIT_USER_TAGLINE: 'EDIT_USER_TAGLINE',
  POST_USER_TAGLINE: 'POST_USER_TAGLINE',
  POST_USER_TAGLINE_SUCCESS: 'POST_USER_TAGLINE_SUCCESS',
  POST_USER_TAGLINE_FAILED: 'POST_USER_TAGLINE_FAILED',

  EDIT_USER_COLOR: 'EDIT_USER_COLOR',
  POST_USER_COLOR: 'POST_LOCAL_COLOR',
  POST_USER_COLOR_SUCCESS: 'POST_USER_COLOR_SUCCESS',
  POST_USER_COLOR_FAILED: 'POST_USER_COLOR_FAILED',

  EDIT_USER_ICON: 'EDIT_USER_ICON',
  POST_USER_ICON: 'POST_LOCAL_COLOR',
  POST_USER_ICON_SUCCESS: 'POST_USER_ICON_SUCCESS',
  POST_USER_ICON_FAILED: 'POST_USER_ICON_FAILED',

  CANCEL_EDIT: 'CANCEL_EDIT',

  FOLLOW_USER: 'FOLLOW_USER',
  FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
  FOLLOW_USER_FAILED: 'FOLLOW_USER_FAILED',

  UNFOLLOW_USER: 'UNFOLLOW_USER',
  UNFOLLOW_USER_SUCCESS: 'UNFOLLOW_USER_SUCCESS',
  UNFOLLOW_USER_FAILED: 'UNFOLLOW_USER_FAILED',

  POLL_USERS: 'POLL_USERS',
  POLL_USERS_SUCCESS: 'POLL_USERS_SUCCESS',
  POLL_USERS_FAILED: 'POLL_USERS_FAILED',

  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILED: 'GET_USERS_FAILED'
}
